### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by zhuwenbing** [shazi7804/nginxauto#1]
求助：安装失败，详细信息如下，

./nginx-auto.sh install

Welcome to the nginx automatic installation

Nginx installation is starting

Nginx version: 1.11.6
SSL: OpenSSL 1.0.1e-fips
Headers: 0.31
PageSpeed: 1.11.33.4

Verify dependencies  [OK]
Downloading ngx_pagespeed  [OK]
Downloading libbrotli  [OK]
Configuring libbrotli  [OK]
Compiling libbrotli  [OK]
Installing libbrotli  [OK]
ln: creating symbolic link `/lib64': File exists
Downloading ngx_brotli  [OK]
Downloading ngx_headers_more  [OK]
Downloading GeoIP databases  [OK]
Downloading nginx  [OK]
Downloading nginx.conf  [Fail]

上面的 ln: creating symbolic link `/lib64': File exists 是因为安装了多遍！
另外，可以弄个Debian版本的吗？谢谢！

**Comment by shazi7804** [comment]
Hi zhuwenbing

已修正 config URI、softlink file exists 問題

You can follow [Angristan/nginx-autoinstall](https://github.com/Angristan/nginx-autoinstall) Debian version.

Thanks.

**Comment by zhuwenbing** [comment]
I've got it, thank you @shazi7804
